[package]
name = "sbtserver"
version = "0.1.0"
authors = ["Ophirr33 <Coghlan.Ty@gmail.com>"]

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
mio = "0.6.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
